### ISSUE TITLE
ImportError: No module named gi.repository

### ISSUE THREAD

**Issue by febs** [kdani3/i3-gnome-pomodoro#11]
I got that error after running 

`python pomodoro-client.py status`

I tried installing "gi" with "sudo -H pip install gi"

and I now get _ImportError: No module named repository_

Maybe something is missing in the documentation? Running Ubuntu 17.10. Thanks

**Comment by pedrols** [comment]
I'm also having this issue on Ubuntu 16.04

**Comment by kantord** [comment]
`sudo apt-get install python-gobject` ?

**Comment by febs** [comment]
Thanks for your reply.

Now I get this:

```
from gi.repository import Gio
ImportError: No module named repository
```

**Comment by nadvornix** [comment]
@febs I had same error. It was fixed after installing [pygobject](https://www.anaconda.com/) from anaconda:

`conda install -c conda-forge pygobject`

**Comment by jeremymreed** [comment]
See pull request [13](https://github.com/kantord/i3-gnome-pomodoro/pull/13)

This PR should help with this issue.
