### ISSUE TITLE
Readme typo in repo path

### ISSUE THREAD

**Issue by julianoes** [kdani3/i3-gnome-pomodoro#12]
First of all, thanks for your work, I got this running!

It looks like you have this typo in the path 3 times in the bottom of the README.md:
```
exec python ~/repos/i3-gnome-/pomodoro-client.py daemon &
```
->
```
exec python ~/repos/i3-gnome-pomodoro/pomodoro-client.py daemon &
```

https://github.com/kantord/i3-gnome-pomodoro#suppressing-dunst-notifications-and-disabling-workspaces

**Comment by jakob1379** [comment]
Sorry for the spam. Had some issues with a branch overwriting master -.-
