### ISSUE TITLE
GLib.Error thrown when gnome-pomodoro isn't running

### ISSUE THREAD

**Issue by jeremymreed** [kdani3/i3-gnome-pomodoro#14]
If gnome-pomodoro isn't running, a GLib.Error is thrown.  The exception gets stringified, and is displayed in the bar.

To reproduce:
1. Make sure gnome-pomodoro isn't running
2. Execute python pomodoro-client.py status

**Comment by jakob1379** [comment]
Running manjaro i3. Not able to reproduce.

**Comment by kantord** [comment]
I cannot reproduce this at the moment. Feel free to reopen if you are facing this issue
