### ISSUE TITLE
issue on delayed notifications

### ISSUE THREAD

**Issue by iovanom** [kdani3/i3-gnome-pomodoro#16]
When the break phase is started all notifications from active phase are displayed. I think the logic should be the opposite.

**Comment by kantord** [comment]
What do you mean by opposite logic? That the notification should be displayed in the active period, and hidden during the break?

The main purpose of this is getting rid of distractions during the active period, not the idea of having them during the breaks. In fact it doesn't matter if you are on a break or have pomodoros disabled, you'll still see notifications.

**Comment by iovanom** [comment]
oh, then this is clear for me. I thought that we need to show the notification after the break to not skip some notifications when we are on the break :)
then sorry for this comment

**Comment by kantord** [comment]
That's ok!

Also, I'm not against adding the possibility of overriding this behavior, if your use case requires something else. I'll gladly take a MR :-)
