### ISSUE TITLE
executing cmd's via shortcuts or external scripts isn't working

### ISSUE THREAD

**Issue by lockejan** [kdani3/i3-gnome-pomodoro#24]
First of all, thanks for the implementation.

gnome-pomodoro works and I can call it via CLI like:
`~/bin/i3-gnome-pomodoro/pomodoro-client.py status` 
which gives me the expected status.

I can use all example cmd's to change the state, but only via CLI.
If I try to use shortcuts, they are simply ignored.

I've already checked my keycodes and tried different dummy commands to verify that everything is okay on that site, for e.g. `bindsym $mod+F9 exec "notify-send foo"`.

This indeed works with shortcuts, but unfortunately none of the `pomodoro-client` cmd's work with shortcuts.

I'm just using the example shortcuts like this:

```
bindsym $mod+F9 exec "python ~/bin/i3-gnome-pomodoro/pomodoro-client.py start"
bindsym $mod+F10 exec "python ~/bin/i3-gnome-pomodoro/pomodoro-client.py toggle"
bindsym $mod+F11 exec "python ~/bin/i3-gnome-pomodoro/pomodoro-client.py skip"
bindsym $mod+F12 exec "python ~/bin/i3-gnome-pomodoro/pomodoro-client.py stop"
```

Furthermore I can't seem to get it displayed within i3status.
I created the described example script and made it executable, but it seems to be the same problem as for the shortcuts.
```
#!/usr/bin/env bash

i3status | while :
do
   read line
   pomodoro=`python ~/bin/i3-gnome-pomodoro/pomodoro-client.py status`
   echo "$pomodoro| $line" || exit 1
done
```

It does work to execute this script directly via CLI. See the screenshot:
![image](https://user-images.githubusercontent.com/25434434/74136637-b0e02280-4bee-11ea-8d12-fe51089862d6.png)

If I use any other dummy cmd instead of the provided one in `i3status.sh`, e.g. `$(lscpu | head -1 | awk '{print $2}')` it get's displayed in my status bar.

I'm on Fedora31, using i3 4.17.1 and i3status 2.13.

My i3config: https://pastebin.com/869HKXiK

**Comment by lockejan** [comment]
When invoking `i3bar --bar_id=bar-0` from CLI the pomodoro timer is displayed.
Maybe it's an i3 related issue???

**Comment by kantord** [comment]
at first glance, I would try to debug the `python` part there. Does that python command exist? Is it a compatible version? I understand that it exists in the terminal where you tried it, but maybe somehow it's overwritten or not defined in the `exec` in i3? :thinking:  Just guessing there tho

Another possibility is that there's something wrong with (relative) file paths

**Comment by kantord** [comment]
So yeah I'd think this might be about environment variables or something like that

**Comment by lockejan** [comment]
Hmm, yeah, it has to be. I'm using python 3.8.1 with pyenv, but the `#!/usr/bin/env python` takes that into account.

So I just made a small test script `~/bin/test.py` to verify that:
```python
#!/usr/bin/env python

import os, sys

if len(sys.argv) > 0:
    os.system(f"notify-send {str(sys.argv[1])}")
else:
    os.system("notify-send 'hello'")
```

and attached it in the same manner to a keybinding in my i3config

`bindsym $mod+F9 exec "python ~/bin/test.py i3status"`

This works right off the bat.🤔😕
I tested it with python 3.6.9 as well and it doesn't make any difference.😬

**Comment by lockejan** [comment]
Okay, I figured it out. It has to do with i3 environment handling. It seems to ignore my pyenv env and falls back to the distros python which hasn't the deps installed.
After installing them it works. Gonna open a ticket for i3 then.
Thanks for your input.

**Comment by kantord** [comment]
It isn't an issue with i3 itself. It depends a lot on how your i3 is configured and launched. See: https://www.reddit.com/r/i3wm/comments/72oiwl/how_do_i_set_environment_variables_so_that_they/

**Comment by lockejan** [comment]
Okay, so I just created .profile in my `$HOME` and added this line to make my x session aware of pyenv:

```bash
export PATH=$($HOME/.pyenv/bin/pyenv root)/shims:/usr/local/bin:/usr/bin:/bin:$PATH
```

I'm not sure if this is good practice but it solves the issue for me.😀
