### ISSUE TITLE
If not necessary - please change dependency to i3ipc-python

### ISSUE THREAD

**Issue by jakob1379** [kdani3/i3-gnome-pomodoro#31]
I have found that a lot of i3 packages are in conflict with i3-gnome-pomodoro as it uses the i3ipc-python-git instead of i3ipc-python. If there is no special reason for this, please consider changing this dependency.

Cheers!

**Comment by kantord** [comment]
You are talking about the Arch package, right? It's not maintained here, I am not in contact with the person who created it

**Comment by jakob1379** [comment]
Thanks for answering. I'll figure something out then. Thought the arch repo just pointed to the git. Time to learn :D
