### ISSUE TITLE
pomodoro always auto continues after break

### ISSUE THREAD

**Issue by vereym** [kdani3/i3-gnome-pomodoro#43]
Hey, so I saw that there is a thread about gnome-pomodoro not continuing after the break, but for me, it's the exact opposite.
After breaks (independent of activity on the pc) the next pomodoro starts automatically. 

This often throws me off because I try to always step away from the pc but often fail to arrive exactly after 5 minutes and then have to manually open the gnome-pomodoro and reset the timer.

Because of #8 it seems to me that this is not the default behaviour, so wanted to ask if someone else is experiencing the same and could point me into a direction to fix this.

My setup is i3 with polybar.

**Comment by kantord** [comment]
Hi @jedth , does this also happen if you use gnome-pomodoro without i3-gnome-pomodoro? I think that i3-gnome-pomodoro should not be influencing this behavior, it should just be reflecting the status of gnome-pomodoro itself. It's possible that your issue is with gnome-pomodoro

**Comment by vereym** [comment]
Hey sry for the late reply, I had no access to my pc so couldn't test it.
But it's exactly how you said, and that makes total sense …duh 🤦🏻‍♂️ 
I'll try my luck at the gnome-pomodoro repo then 👍🏻
