### ISSUE TITLE
[feature-request]-TODO list

### ISSUE THREAD

**Issue by riivanov** [kdani3/i3-gnome-pomodoro#46]
I would really like to track how much time I spend on what pomodoro. I don't know if this is within the scope of the project. I was thinking about making a pull request, but I figured I'd make an issue first.

What I would like, is the ability to have a TODO list, where each TODO is a pomodoro, and have the current item in the list displayed to the left of the remaining time.

![i3-gnome-pomodoro- feat -TODO-list-2024-01-04_14-28](https://github.com/kantord/i3-gnome-pomodoro/assets/107855902/99c1d6c8-354d-4045-8b7b-b6e85548dc44)

**Comment by kantord** [comment]
This could be in the scope of i3-gnome-pomodoro but not in the sense of having a built-in support for TODO lists, but in the sense of interfacing with another app that supports this already.

Ideally this would be done either through a built-in feature of gnome-pomodoro itself, or if that is not available, it would ideally be done using a 3rd app that can already cooperate with gnome-pomodoro.

If you have some specific suggestions I would like to hear them!

**Comment by kantord** [comment]
Closing this, as it is out of scope for this project and rather belongs to gnome-pomodoro itself, as this project is a mere wrapper for gnome-pomodoro.

However one potential option to solve this is to replace the backend in this project with something that supports TODO lists out of the box. Feel free to reopen if you have a suggestion for such a backend.

Another, perhaps better, option is to use a backend that can integrate with a TODO list app. I think that would be a better solution, as it would be a little bit limiting if users are forced to use one specific TODO list app.
