### ISSUE TITLE
[feature-request]-config file

### ISSUE THREAD

**Issue by riivanov** [kdani3/i3-gnome-pomodoro#47]
I would like to have the ability to configure the length of each pomodoro, each short break, and each long break. I suppose the simplest possibility is a config file in `/etc` or `~/.i3-gnome-pomodoro/config`.

**Comment by kantord** [comment]
I think this is already a feature in [gnome-pomodoro](https://github.com/gnome-pomodoro/gnome-pomodoro) itself, so you should be able to configure it there. I think it can be configured through their GUI, and hopefully a dotfile/config file based approach is also supported

I guess a config file might be useful for specific features in i3-gnome-pomodoro, like configuring the output format or something similar, but not for overriding features of gnome-pomodoro itself.

**Comment by riivanov** [comment]
I suppose I should read through their source code or hunt in the repo? There is no manual page describing this as I would expect. Of course this is also something that could be contributed.

**Comment by riivanov** [comment]
I did find these two links after digging somewhat:
- [config-wiki](https://github.com/gnome-pomodoro/gnome-pomodoro/wiki/Configuration)
-  [g-schema-file](https://github.com/gnome-pomodoro/gnome-pomodoro/blob/3b293bfb01cb834c6b68e0ad25cb0619d5f84b7b/data/org.gnome.pomodoro.gschema.xml#L4)

**Comment by kantord** [comment]
![2024-01-05-152924_680x885_scrot](https://github.com/kantord/i3-gnome-pomodoro/assets/3704904/26b3736a-a22d-4ca9-b9e5-e1b7c9b2320b)
as far as GUI based settings go, this is what I found

**Comment by riivanov** [comment]
Can I ask how?

**Comment by riivanov** [comment]
Oh, I see. I really didn't do much research before asking the question. My apologies.

So, I also wasn't aware that `i3-gnome-pomodoro` just wrapped `gnome-pomodoro`. To be honest I didn't know `gnome-pomodoro` was installed... All I remember doing is `yay -S i3-gnome-pomodoro`.

So the above screen is available if you run:

`gnome-pomodoro --preferences`

And these settings do in fact change the behavior of `i3-gnome-pomodoro`.

I could see this thread added as part of the README.

And one more thing to note, at least on my machine (famous last words), the installation was a bit bumpy. I don't remember specifics, but it was not as smooth as I'd like. Yet something else that could be contributed.

Overall this is a great port to i3. I love it. I just wish it had a man page. `man i3-gnome-pomodoro` would be awesome. Just because that's how you get used to looking for help in Linux.

Thanks for the feedback.

**Comment by kantord** [comment]
> Oh, I see. I really didn't do much research before asking the question. My apologies.
> 
> So, I also wasn't aware that `i3-gnome-pomodoro` just wrapped `gnome-pomodoro`. To be honest I didn't know `gnome-pomodoro` was installed... All I remember doing is `yay -S i3-gnome-pomodoro`.
> 
> So the above screen is available if you run:
> 
> `gnome-pomodoro --preferences`
> 
> And these settings do in fact change the behavior of `i3-gnome-pomodoro`.
> 
> I could see this thread added as part of the README.
> 
> And one more thing to note, at least on my machine (famous last words), the installation was a bit bumpy. I don't remember specifics, but it was not as smooth as I'd like. Yet something else that could be contributed.
> 
> Overall this is a great port to i3. I love it. I just wish it had a man page. `man i3-gnome-pomodoro` would be awesome. Just because that's how you get used to looking for help in Linux.
> 
> Thanks for the feedback.

Ok, so maybe a potential feature could be to simply add a `--preferences` flag to i3-gnome-pomodoro which would just call `gnome-pomodoro --preferences`. This is not really a required feature but it could just save a couple minutes of research without bloating this project too much.

Regarding man page, I have never created one. If you are familiar how to create one for Python packages, you could help me out :pray:  this project uses Poetry btw.

Also I don't maintain the Arch package itself. Though I am an Arch user, nowadays I do use `pipx` to install most standalone Python applications

**Comment by riivanov** [comment]
Ok,

I'm not familiar with man pages, but I doubt it's that hard. Sure I can look into it. Making no promises time wise as I'm about to start a new job.

The `--preferences` flag seems to me the most logical way to handle that.

Now I recall, yes it was the AUR package that did not install correctly. `pipx` install worked just fine. So maybe another opportunity to contribute there.

I don't know much python, but I really do use this project every day, so my idea was either to clone it, or see if anybody would respond to the issues and contribute something.

Cheers
