### ISSUE TITLE
cairo not found

### ISSUE THREAD

**Issue by romseguy** [kdani3/i3-gnome-pomodoro#49]
Hello,

Do you know how to solve this error?

I'm using i3 4.22 on Debian 12 (Linux Mint LMDE 6 FAYE)

Thank you

    $ pipx install i3-gnome-pomodoro
    Fatal error from pip prevented installation. Full pip output in file:
        ~/.local/pipx/logs/cmd_2024-06-19_14.35.19_pip_errors.log
    
    pip seemed to fail to build package:
        pycairo
    
    Some possibly relevant errors from pip install:
        error: subprocess-exited-with-error
        Package cairo was not found in the pkg-config search path.
        Package 'cairo', required by 'virtual:world', not found

<details><summary>cmd_2024-06-19_14.35.19_pip_errors.log</summary>
<p>

PIP STDOUT
----------
Collecting i3-gnome-pomodoro
  Downloading i3_gnome_pomodoro-0.1.0-py3-none-any.whl.metadata (7.4 kB)
Collecting blinkstick<2.0.0,>=1.2.0 (from i3-gnome-pomodoro)
  Downloading BlinkStick-1.2.0-py3-none-any.whl.metadata (3.7 kB)
Collecting click<9.0.0,>=8.1.7 (from i3-gnome-pomodoro)
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting i3ipc<3.0.0,>=2.2.1 (from i3-gnome-pomodoro)
  Downloading i3ipc-2.2.1-py3-none-any.whl.metadata (4.7 kB)
Collecting pydbus<0.7.0,>=0.6.0 (from i3-gnome-pomodoro)
  Downloading pydbus-0.6.0-py2.py3-none-any.whl.metadata (3.8 kB)
Collecting pygobject<4.0.0,>=3.46.0 (from i3-gnome-pomodoro)
  Downloading pygobject-3.48.2.tar.gz (715 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 715.2/715.2 kB 2.6 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'

PIP STDERR
----------
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      Collecting meson-python>=0.12.1
        Downloading meson_python-0.16.0-py3-none-any.whl.metadata (4.1 kB)
      Collecting pycairo>=1.16
        Downloading pycairo-1.26.0.tar.gz (346 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 346.9/346.9 kB 1.8 MB/s eta 0:00:00
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting meson>=0.63.3 (from meson-python>=0.12.1)
        Downloading meson-1.4.1-py3-none-any.whl.metadata (1.8 kB)
      Collecting packaging>=19.0 (from meson-python>=0.12.1)
        Downloading packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
      Collecting pyproject-metadata>=0.7.1 (from meson-python>=0.12.1)
        Downloading pyproject_metadata-0.8.0-py3-none-any.whl.metadata (3.0 kB)
      Downloading meson_python-0.16.0-py3-none-any.whl (26 kB)
      Downloading meson-1.4.1-py3-none-any.whl (937 kB)
         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 937.7/937.7 kB 2.6 MB/s eta 0:00:00
      Downloading packaging-24.1-py3-none-any.whl (53 kB)
         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.0/54.0 kB 1.6 MB/s eta 0:00:00
      Downloading pyproject_metadata-0.8.0-py3-none-any.whl (7.5 kB)
      Building wheels for collected packages: pycairo
        Building wheel for pycairo (pyproject.toml): started
        Building wheel for pycairo (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Building wheel for pycairo (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [15 lines of output]
            running bdist_wheel
            running build
            running build_py
            creating build
            creating build/lib.linux-x86_64-cpython-311
            creating build/lib.linux-x86_64-cpython-311/cairo
            copying cairo/__init__.py -> build/lib.linux-x86_64-cpython-311/cairo
            copying cairo/__init__.pyi -> build/lib.linux-x86_64-cpython-311/cairo
            copying cairo/py.typed -> build/lib.linux-x86_64-cpython-311/cairo
            running build_ext
            Package cairo was not found in the pkg-config search path.
            Perhaps you should add the directory containing `cairo.pc'
            to the PKG_CONFIG_PATH environment variable
            Package 'cairo', required by 'virtual:world', not found
            Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']' returned non-zero exit status 1.
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for pycairo
      Failed to build pycairo
      ERROR: Could not build wheels for pycairo, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

</p>
</details>

**Comment by pauljamesharper** [comment]
I had the same on Ubuntu 24.04.  I had to do the following:

`sudo apt-get install pkg-config &&
sudo apt-get install libcairo2-dev &&
sudo apt install libgirepository1.0-dev &&
pipx install i3-gnome-pomodoro`

I hope that works for you as Debian is similar (but not the same) as Ubuntu.

**Comment by romseguy** [comment]
I did what you said and got : **cairo/bufferproxy.c:32:10: fatal error: Python.h: No such file or directory**

    $ pipx install i3-gnome-pomodoro
    
    Fatal error from pip prevented installation. Full pip output in file:
        /home/x240/.local/pipx/logs/cmd_2024-06-23_20.03.14_pip_errors.log
    
    pip seemed to fail to build package:
        pycairo
    
    Some possibly relevant errors from pip install:
        error: subprocess-exited-with-error
        cairo/bufferproxy.c:32:10: fatal error: Python.h: No such file or directory
        error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1

**Comment by kantord** [comment]
> I did what you said and got : **cairo/bufferproxy.c:32:10: fatal error: Python.h: No such file or directory**
> 
> ```
> $ pipx install i3-gnome-pomodoro
> 
> Fatal error from pip prevented installation. Full pip output in file:
>     /home/x240/.local/pipx/logs/cmd_2024-06-23_20.03.14_pip_errors.log
> 
> pip seemed to fail to build package:
>     pycairo
> 
> Some possibly relevant errors from pip install:
>     error: subprocess-exited-with-error
>     cairo/bufferproxy.c:32:10: fatal error: Python.h: No such file or directory
>     error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
> ```

I am not sure how your operating system works, perhaps you need to install a package like `python-dev` or sth similar. But in any case I wonder why you have this problem in the first place, I think this is not related to a direct dependency of i3-gnome-pomodoro itself.


Do you have gnome-pomodoro installed?

**Comment by romseguy** [comment]
I have both python-dev@3.11.2 and gnome-pomodoro@0.22.1 installed

![Capture d’écran du 2024-07-27 15-56-14](https://github.com/user-attachments/assets/dd39c0b0-1fee-4ae5-aa4c-08eed4b85a55)



> $ gnome-pomodoro --version
Pomodoro 0.22.1

Problem could be I used [pyenv](https://github.com/pyenv/pyenv) even though :

> $ python --version
Python 3.12.4

> $ pip --version
pip 24.0 from ~/.pyenv/versions/3.12.4/lib/python3.12/site-packages/pip (python 3.12)

> $ pipx --version
1.1.0

I got this in my .zshrc

> export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

**Comment by kantord** [comment]
I feel like pyenv should not be a problem :thinking: 


I looked into this and pycairo is a dependency of pygobject which itself is basically the most essential dependency of this project since it is what allows it to communicate with gnome-pomodoro. So there is really no way around this, you have to have pycairo working. 

At the end of the day all evidence points towards that the problem is not with i3-gnome-pomodoro, but either with pycairo or something in your system.

Generally the error you are getting is because you are trying to install something that builds code locally on your computer and requires Python's header files. Here's a thread about that: https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory

Here's a similar thread I found in another project: https://github.com/3b1b/manim/issues/751 

And another one: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360006405400-cairo-device-c-30-10-fatal-error-Python-h-No-such-file-or-directory-SOLVED

If those don't help, I would recommend going to pycairo itself and raising an issue there: https://github.com/pygobject/pycairo. If you do so, please link this issue there, that way GitHub will create a 2-way link that will be accessible to posterity
