### ISSUE TITLE
ImportError: No module named pydbus

### ISSUE THREAD

**Issue by jjnilton** [kdani3/i3-gnome-pomodoro#5]
I'm trying to install the requirements by using: 

```
$ sudo -H pip install requirements.txt 
Collecting requirements.txt
  Could not find a version that satisfies the requirement requirements.txt (from versions: )
No matching distribution found for requirements.txt
```
```
$ python pomodoro-client.py 
Traceback (most recent call last):
  File "pomodoro-client.py", line 6, in <module>
    from pydbus import SessionBus
ImportError: No module named pydbus
```
``` 
$ sudo -H pip install pydbus
Requirement already satisfied: pydbus in /usr/local/lib/python3.5/dist-packages
```

Tried to reinstall `python-dbus` and `python3-dbus` packages, but did not work.

Any ideas?

**Comment by kantord** [comment]
Have you tried installing it in a new virtualenv? Also, `python` is Python 3.6 on my computer. I haven't really tested it with other Python versions. You might need to use a different Python version. You can do that with a virtualenv, plus many distros provide different versions of Python under different names, such as `python2`, `python3`, `python 27`, etc. Same goes for `pip`.
