### ISSUE TITLE
Specify python version

### ISSUE THREAD

**Issue by flanaras** [kdani3/i3-gnome-pomodoro#7]
Hello,
I would like to ask you to add the python version (2/3) that the script is appropriate for.
You could also add the environment that you have tested it on.

**Comment by kantord** [comment]
Sure. I added it to README.md, see this commit: https://github.com/kantord/i3-gnome-pomodoro/commit/f8eae8fe2f2618447f8b05a115b5d6c9cb1b5f94

If you have trouble running it, you are welcome to open another issue with your environment details. Also, If you have an idea or solution that could make the configuration easier, pull requests are welcome :-) Even if it's specific to your environment.
