### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by manufactory** [kdani3/i3-gnome-pomodoro#9]
This is a really useful piece of software! I created an Arch Linux package for it. Unfortunately, it's unclear if it can be used at all, because it lacks a licence.

**Comment by kantord** [comment]
Good point. I've added a license.

Thanks for creating a package. Can you please add instructions to https://github.com/kantord/i3-gnome-pomodoro/blob/master/README.md?

**Comment by manufactory** [comment]
Cool Thanks! I'll update the package and and install instructions as soon as I can find time.
